/* eslint-disable react-hooks/exhaustive-deps */
import Head from 'next/head';
import styles from '@/styles/Home.module.css';

import { useRouter } from 'next/router';
import { useEffect } from 'react';
import axios from 'axios';

export default function SingUp() {
  const location = useRouter();
  console.log(location.query.code);

  const authKakao = async () => {
    const res = await axios.post(
      'https://kauth.kakao.com/oauth/token',
      `grant_type=authorization_code&client_id=${process.env.NEXT_PUBLIC_KAKAO_API}&redirect_uri=${process.env.NEXT_PUBLIC_KAKAO_REDIRECT_URL}&code=${location.query.code}`,
      {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    );

    console.log(res);

    const userInfo = await axios.get(`https://kapi.kakao.com/v2/user/me`, {
      headers: {
        Authorization: `Bearer ${res.data.access_token}`,
        'Content-type': 'application/x-www-form-urlencoded;charset=utf-8',
      },
    });

    console.log(userInfo);
  };
  useEffect(() => {
    if (location.query.code) {
      authKakao();
    }
  }, [location]);

  return (
    <>
      <Head>
        <title>회원가입</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>SignUp</h1>
    </>
  );
}
